name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: nvencer98/LEETCODE@ref
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.CSRF }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-folder
